"https://{default}/":
  type: upstream
  upstream: "app:http"
  cache:
    enabled: false
  headers:
    X-Robots-Tag: "noindex, nofollow, noarchive, noimageindex"
    Referrer-Policy: "no-referrer"
    X-Frame-Options: "DENY"
    X-Content-Type-Options: "nosniff"
    Permissions-Policy: "geolocation=(), microphone=(), camera=()"
